version: '3'
services: 
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
  logger:
    image: meongbego/cinlog
    restart: always
    ports:
      - 3000:3000
    environment:
      - GIN_MODE=release
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=3000
      - SERVER_TIMEZONE=Asia/Jakarta
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=nemo
      - MONGO_USER=
      - MONGO_PASSWORD=
      - LOGGER_DRIVER=mongo
    command: ./main -e production
    tty: true
    depends_on:
      - mongo